# Generated by Django 4.0.6 on 2022-07-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clj_app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
